.PHONY: ps2_bit_rx_strobe_tb
ps2_bit_rx_strobe_tb:
	xelab --prj prj/ps2_bit_rx_strobe_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.ps2_bit_rx_strobe_tb

.PHONY: ps2_shifter_tb
ps2_shifter_tb:
	xelab --prj prj/ps2_shifter_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.ps2_shifter_tb

.PHONY: ps2_shifter_inst_tb
ps2_shifter_inst_tb:
	xelab --prj prj/ps2_shifter_inst_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.ps2_shifter_inst_tb

.PHONY: ps2_byte_parser_tb
ps2_byte_parser_tb:
	xelab --prj prj/ps2_byte_parser_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.ps2_byte_parser_tb

.PHONY: ps2_interface_tb
ps2_interface_tb:
	xelab --prj prj/ps2_interface_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.ps2_interface_tb

.PHONY: ps2_interface_test_tb
ps2_interface_test_tb:
	xelab --prj prj/ps2_interface_test_tb.prj -debug all -O3 -rangecheck -stat \
		-v 0 xil_defaultlib.ps2_interface_test_tb

